export interface ColoresPrincipales {
  id: number;
  backgroundColor: string,
  color: string,
  borderColor: string,
  seleccionado: boolean,


}

export const _vacoloresPrincipales: ColoresPrincipales[] = [
  {
    id: 1,
    backgroundColor: "#DAF7A6",
    color: "#DAF7A6",
    borderColor: "#DAF7A6",
    seleccionado: false,
  },
  {
    id: 2,
    backgroundColor: "#FFC300",
    color: "#FFC300",
    borderColor: "#FFC300",
    seleccionado: false,
  },
  {
    id: 3,
    backgroundColor: "#FF5733",
    color: "#FF5733",
    borderColor: "#FF5733",
    seleccionado: false,
  },
  {
    id: 4,
    backgroundColor: "#C70039",
    color: "#C70039",
    borderColor: "#C70010",
    seleccionado: false,
  },
  {
    id: 5,
    backgroundColor: "#900C3F",
    color: "#900C3F",
    borderColor: "#900C3F",
    seleccionado: false,
  },
  {
    id: 6,
    backgroundColor: "#581845",
    color: "#581845",
    borderColor: "#581845",
    seleccionado: false,
  },
  {
    id: 7,
    backgroundColor: "#3498db",
    color: "#3498db",
    borderColor: "#3498db",
    seleccionado: false,
  },
  {
    id: 8,
    backgroundColor: "#1a5276",
    color: "#1a5276",
    borderColor: "#1a5276",
    seleccionado: false,
  },
  {
    id: 9,
    backgroundColor: "#154360",
    color: "#154360",
    borderColor: "#154360",
    seleccionado: false,
  },
  {
    id: 10,
    backgroundColor: "#d2b4de",
    color: "#d2b4de",
    borderColor: "#d2b4de",
    seleccionado: false,
  },
  {
    id: 11,
    backgroundColor: "#a569bd",
    color: "#a569bd",
    borderColor: "#a569bd",
    seleccionado: false,
  },
  {
    id: 12,
    backgroundColor: "#5dade2",
    color: "#5dade",
    borderColor: "#5dade1",
    seleccionado: false,
  },
  {
    id: 13,
    backgroundColor: "#a04000",
    color: "#a04000",
    borderColor: "#a04000",
    seleccionado: false,
  },
  {
    id: 14,
    backgroundColor: "#784212",
    color: "#784212",
    borderColor: "#784212",
    seleccionado: false,
  },
  {
    id: 15,
    backgroundColor: "#515a5a",
    color: "#515a5a",
    borderColor: "#515a5a",
    seleccionado: false,
  },
  {
    id: 16,
    backgroundColor: "#707b7c",
    color: "#707b7c",
    borderColor: "#707b7c",
    seleccionado: false,
  },
  {
    id: 17,
    backgroundColor: "#566573",
    color: "#566573",
    borderColor: "#566573",
    seleccionado: false,
  },
  {
    id: 18,
    backgroundColor: "#b2babb",
    color: "#b2babb",
    borderColor: "#b2babb",
    seleccionado: false,
  },
  {
    id: 19,
    backgroundColor: "#f0b27a",
    color: "#f0b27a",
    borderColor: "#f0b27a",
    seleccionado: false,
  },
  {
    id: 20,
    backgroundColor: "#f5b041",
    color: "#f5b041",
    borderColor: "#f5b041",
    seleccionado: false,
  },
  {
    id: 21,
    backgroundColor: "#f4d03f",
    color: "#f4d03f",
    borderColor: "#f4d03f",
    seleccionado: false,
  },
  {
    id: 22,
    backgroundColor: "#52be80",
    color: "#52be80",
    borderColor: "#52be10",
    seleccionado: false,
  },
  {
    id: 23,
    backgroundColor: "#48c9b0",
    color: "#48c9b0",
    borderColor: "#48c9b0",
    seleccionado: false,
  },
  {
    id: 24,
    backgroundColor: "#5499c7",
    color: "#5499c7",
    borderColor: "#5499c7",
    seleccionado: false,
  },
  {
    id: 25,
    backgroundColor: "#00cc00",
    color: "#00cc00",
    borderColor: "#00cc00",
    seleccionado: false,
  },
  {
    id: 26,
    backgroundColor: "#ff6600",
    color: "#ff6600",
    borderColor: "#ff6600",
    seleccionado: false,
  },
  {
    id: 27,
    backgroundColor: "#ffff66",
    color: "#ffff66",
    borderColor: "#ffff66",
    seleccionado: false,
  },
  {
    id: 28,
    backgroundColor: "#ff3300",
    color: "#ff3300",
    borderColor: "#ff3300",
    seleccionado: false,
  },
];